"""setting relationships of tables

Revision ID: 1fd59ac05958
Revises: 85b4a2ed9482
Create Date: 2018-05-01 22:23:16.243503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd59ac05958'
down_revision = '85b4a2ed9482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Assortments', 'Cuisine', ['id_cuisine'], ['id'])
    op.create_foreign_key(None, 'Assortments', 'Category_Assortment', ['id_category_assortment'], ['id'])
    op.create_foreign_key(None, 'Assortments', 'Establishment', ['id_establishment'], ['id'])
    op.create_foreign_key(None, 'Cuisine_of_Est', 'Cuisine', ['id_cuisine'], ['id'])
    op.create_foreign_key(None, 'Cuisine_of_Est', 'Establishment', ['id_establishment'], ['id'])
    op.create_foreign_key(None, 'Order', 'Subsidiary', ['id_subsidiary'], ['id'])
    op.create_foreign_key(None, 'Order', 'Client', ['id_client'], ['id'])
    op.create_foreign_key(None, 'Order_Of_Assortment', 'Assortments', ['id_assortment'], ['id'])
    op.create_foreign_key(None, 'Order_Of_Assortment', 'Order', ['id_order'], ['id'])
    op.create_foreign_key(None, 'Subsidiary', 'Establishment', ['id_establishment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Subsidiary', type_='foreignkey')
    op.drop_constraint(None, 'Order_Of_Assortment', type_='foreignkey')
    op.drop_constraint(None, 'Order_Of_Assortment', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Cuisine_of_Est', type_='foreignkey')
    op.drop_constraint(None, 'Cuisine_of_Est', type_='foreignkey')
    op.drop_constraint(None, 'Assortments', type_='foreignkey')
    op.drop_constraint(None, 'Assortments', type_='foreignkey')
    op.drop_constraint(None, 'Assortments', type_='foreignkey')
    # ### end Alembic commands ###
