"""first version of db without relationships

Revision ID: 85b4a2ed9482
Revises: 
Create Date: 2018-04-30 17:10:15.338693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b4a2ed9482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assortments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=True),
    sa.Column('title_assortment', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_cuisine', sa.Integer(), nullable=True),
    sa.Column('id_category_assortment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Category_Assortment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_Category_Assortment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.Text(), nullable=True),
    sa.Column('last', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('personal_account', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('block_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cuisine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_cuisine', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cuisine_of_Est',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=True),
    sa.Column('id_cuisine', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Establishment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_establishment', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lon', sa.Numeric(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_subsidiary', sa.Integer(), nullable=True),
    sa.Column('dateAndTime_of_order', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('order_issued', sa.Boolean(), nullable=True),
    sa.Column('confirmation_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order_Of_Assortment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_assortment', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price_of_order', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subsidiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_establishment', sa.Integer(), nullable=True),
    sa.Column('title_subsidiary', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lon', sa.Numeric(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('mobile_number', sa.Integer(), nullable=True),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subsidiary')
    op.drop_table('Order_Of_Assortment')
    op.drop_table('Order')
    op.drop_table('Establishment')
    op.drop_table('Cuisine_of_Est')
    op.drop_table('Cuisine')
    op.drop_table('Client')
    op.drop_table('Category_Assortment')
    op.drop_table('Assortments')
    # ### end Alembic commands ###
